### ISSUE TITLE
nano Training has been able to achieve good results

### ISSUE THREAD

**Issue by lifeiteng** [lifeiteng/vall-e#1]
# nano config
```
python3 bin/trainer.py \
    --decoder-dim 128 --nhead 4 --num-decoder-layers 4 \
    --max-duration 40 --model-name valle \
    --exp-dir exp/valle_nano_full
```

converging

<img width="1340" alt="截屏2023-01-29 17 08 17" src="https://user-images.githubusercontent.com/3107839/215316526-108bf952-05fb-4377-b3b4-595daad5aefe.png">

**Comment by do-web** [comment]
How do i store the training data and how are they loaded?

**Comment by lifeiteng** [comment]
> How do i store the training data and how are they loaded? Any example?

https://github.com/lifeiteng/valle/blob/main/README.md#training

**Comment by lifeiteng** [comment]
model trained with nano config(about 100x smaller than the paper config) have been able to synthesize human-like speech.

**Comment by lifeiteng** [comment]
<img width="1047" alt="截屏2023-02-07 00 24 49" src="https://user-images.githubusercontent.com/3107839/217033521-8465a80e-f3e5-4dfd-bbdc-dc0550db6143.png">

**Comment by rishikksh20** [comment]
can you upload some samples generated from 3 sec prompt ?

**Comment by lifeiteng** [comment]
> can you upload some samples generated from 3 sec prompt ?

```
cd egs/libritts

python3 bin/infer.py \
    --decoder-dim 128 --nhead 4 --num-decoder-layers 4 --model-name valle \
    --text-prompts "Go to her." \
    --audio-prompts ./prompts/61_70970_000007_000001.wav \
    --output-dir infer/demo_valle_epoch20 \
    --checkpoint exp/valle_nano_v2/epoch-20.pt
```

**Comment by tfriedel** [comment]
what's the expected output? I had some issues relating to some tensors being on cuda, some on cpu and also getting dependencies (especially k2) installed was not straight forward. Anyway, I forced inference on cpu and the result of this command is:
2023-02-07 19:18:18,936 INFO [infer.py:141] synthesize text: To get up and running quickly just follow the steps below.
EOS [61 -> 69]

The resulting wav file is about 5-10kb, so not even a second.

**Comment by entn-at** [comment]
This was the output when I ran the command (converted to opus/webm, Github doesn't accept wav):
[valle_nano_0.webm](https://user-images.githubusercontent.com/10227168/217352234-85d460cf-28ff-4f17-82d6-2b60e12fb46f.webm)

**Comment by lifeiteng** [comment]
> what's the expected output? I had some issues relating to some tensors being on cuda, some on cpu and also getting dependencies (especially k2) installed was not straight forward. Anyway, I forced inference on cpu and the result of this command is: 2023-02-07 19:18:18,936 INFO [infer.py:141] synthesize text: To get up and running quickly just follow the steps below. EOS [61 -> 69]
> 
> The resulting wav file is about 5-10kb, so not even a second.

nano config is too small, so the AR-Decoder may not work well.
re-run to get new(diverse) result.

**Comment by tfriedel** [comment]
@lifeiteng that was it! Had to try a couple of times and sometimes the results were longer and resembled human speech, even if they didn't resemble the input prompt.

**Comment by lifeiteng** [comment]
https://github.com/lifeiteng/vall-e/discussions/22
