### ISSUE TITLE
Preparing the dataset hangs

### ISSUE THREAD

**Issue by TARNATlON** [lifeiteng/vall-e#109]
The prepare bash script has been running for an entire day now (24 hours)
More specifically it hangs when it's being tokenized.

Is there any specific reason to this?
It only creates one file the size of 47.9 MB, so I don't quite think it worked successfully..

**Comment by RuntimeRacer** [comment]
Can you provide more details please, like:
- which script have you been running?
- What is the exact command line and what is the output from the script from start until it hangs up?
- which OS are you on?
- did you do all the steps according to documentation?

**Comment by TARNATlON** [comment]
Nevermind! Just had to update WSL it seems!
Weird though, but oh well, not complaining haha.
