### ISSUE TITLE
Do you have any Chinese TTS results?

### ISSUE THREAD

**Issue by Zhang-Xiaoyi** [lifeiteng/vall-e#117]
how is the results trained on AISHELL-1? do you have any demo results?

**Comment by no-Seaweed** [comment]
I have trained a Chinese TTS model with multiple public datasets. The result is pretty decent (tho the tone is still problematic). It worths to have a try.

**Comment by chenjiasheng** [comment]
Many people have trained very good Chinese models using this repo. 
You can join our wechat group for demos shared by them.
