### ISSUE TITLE
ImportError: libpython3.10.so.1.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by debasishaimonk** [lifeiteng/vall-e#118]
When i try to run 
python3 bin/infer.py --output-dir infer/demos --model-name valle --norm-first true --add-prenet false --decoder-dim 1024 --nhead 16 --num-decoder-layers 12 --text-prompts "KNOT one point one five miles per hour." --audio-prompts /e3/Debasish/VALL_E/vall-e/data/libri2/248-130644-0011.wav --text "To get up and running quickly just follow the steps below." --checkpoint exp_dir/epoch-100.pt 

It's throwing an error like ImportError: libpython3.10.so.1.0: cannot open shared object file: No such file or directory

Traceback (most recent call last):
  File "/e3/Debasish/VALL_E_lifeteing/valle/egs/libritts/bin/infer.py", line 37, in <module>
    from icefall.utils import str2bool
  File "/e3/Debasish/VALL_E_lifeteing/icefall/icefall/__init__.py", line 3, in <module>
    from . import (
  File "/e3/Debasish/VALL_E_lifeteing/icefall/icefall/decode.py", line 20, in <module>
    import k2
  File "/e3/Debasish/VALL_E_lifeteing/valle_lifeteing/valle_lifeteing/lib/python3.10/site-packages/k2/__init__.py", line 23, in <module>
    from _k2 import DeterminizeWeightPushingType
ImportError: libpython3.10.so.1.0: cannot open shared object file: No such file or directory

**Comment by RuntimeRacer** [comment]
I ran into this issue also, something was odd with my anaconda instalation and I tried to run it on plain Windows also.
I recommend either using WSL directly and make sure to use the only the linux filesystem (not the mounted windows partitions), or in case you're on linux already, do a clean reinstall of anaconda and your python env.
Also make sure to follow the instructions in the readme precisely.

In case it helps; sharing a couple of Issues I ran into initially: https://github.com/lifeiteng/vall-e/issues/105

**Comment by debasishaimonk** [comment]
Thanks for replying @RuntimeRacer . I have already rectified this issue by downgrading python3.10 to 3.8 (anaconda env), and seperately built the K2 package on my basis of my CUDA Version. 
Hoping if anyone gets this issue again they can follow up this conversation and can rectify there.

**Comment by debasishaimonk** [comment]
Thanks! so i am closing this issue!!
