### ISSUE TITLE
Multi-Stage training has name conflicts for checkpoint & epoch files when switching from stage 1 to stage 2

### ISSUE THREAD

**Issue by RuntimeRacer** [lifeiteng/vall-e#123]
Hi all, I just wanted to raise awareness for this problem rn since I didn't have time to start looking into fixing it yet:

When switching from stage 1 to stage 2 for NAR training; the function calls to save and cleanup checkpoints + saving epochs internally start counting from epoch 1 and step 0 for the new stage. This results in the following behaviour when saving checkpoints or epoch results:
- As checkpoint files are ordered by step count, the stage 2 checkpoint files will for example be named `checkpoint-2500.pt`; despite the latest AR checkpoint from stage 1 might be named `checkpoint-1500000.pt`. This results in the cleanup algorithm to assume `checkpoint-2500.pt` to be older than checkpoints with higher step count, despite they are from the previous training stage. I noticed this since I was wondering where the 2 checkpoints are that should have just been created, but I only saw the older ones from previous stage in the folder. 
- Once the epoch is finished, the first epoch from stage 1 just gets overwritten.

![image](https://github.com/lifeiteng/vall-e/assets/49956579/20a1a19f-957e-446f-bcb4-9312e785c4ec)

For that reason I moved all the old checkpoint and epoch files into a backup folder. As you can see checkpoint files are starting to count from bottom again:

![image](https://github.com/lifeiteng/vall-e/assets/49956579/1c02aa89-c169-4a74-85ec-4108a22cd4ee)

**Comment by lifeiteng** [comment]
@RuntimeRacer  yes, For big dataset, we should FIX this; but on a smaller dataset(about LibriTTS) `epoch-x.pt` is enough.

**Comment by RuntimeRacer** [comment]
@lifeiteng can you please explain why it's not an issue for small dataset training if Stage 2 epoch files overwrite stage 1 results?
Well I understand that epoch 1 of stage 1 is most probably useless anyways; but it's still confusing, and depending on intention of the training - I could for example imagine someone investigating the process of improvement for a certain prompt over epochs and stages etc. - it is still destroying data.

I think the proper solution here should be, that whenever we start stage 2 training in the same `exp_dir` as stage 1, we should move all .pt files into a separate folder and only keep a copy of the `best-valid-loss-stage1.pt` or `epoch-x.pt` to continue stage 2 training from in that folder, to avoid any confusion and data loss alltogether.

**Comment by lifeiteng** [comment]
@RuntimeRacer yes, we can remove checkpoint-xxx.pt of previous stage. But I'm busy those days, will not have time to refine this repo.
