### ISSUE TITLE
Questions about preparing data

### ISSUE THREAD

**Issue by mikesun4096** [lifeiteng/vall-e#135]
bash prepare.sh --stage -1 --stop-stage 3

This script can not be executed correctly, it seems lhotse cannot download data

The error is :  
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by DB11051998** [comment]
Did you try to do the things separately? I meant not altogether as in prepare.sh script.

**Comment by friendmine** [comment]
you can download the data by yourself.

**Comment by mikesun4096** [comment]
> Did you try to do the things separately? I meant not altogether as in prepare.sh script.

OK, thanks

**Comment by mikesun4096** [comment]
> 

OK, thanks
