### ISSUE TITLE
What do the results sound like?

### ISSUE THREAD

**Issue by Ryan3562** [lifeiteng/vall-e#14]
Hi! I was curious if someone has results of this implementation, I currently can't install it nor test it out.

Thanks so much!

**Comment by MisakaMikoto96** [comment]
> Hi @Ryan3562 I have add infer audios https://github.com/lifeiteng/vall-e/tree/main/egs/libritts/infer

hi, have you ever gotten a good performance on a large data/model?

**Comment by lifeiteng** [comment]
demo page https://lifeiteng.github.io/valle/index.html
