### ISSUE TITLE
question about -- prefix-mode

### ISSUE THREAD

**Issue by jzssz** [lifeiteng/vall-e#144]
1. What is the specific meaning of -- prefix-mode ? I learned "0: no prefix, 1: 0 to random, 2: random to random, 4: chunk of pre or post utterance." But I couldn't understand what it meant. 
2. And does it have to be set the same when train and infer? 
3. When I train ar, can I choose 0, 1, 2, 4? When I train nar, can I choose 0, 1, 2, 4? Must train ar and nar select the same value?
thanks much !

**Comment by chenjiasheng** [comment]
--prefix-mode has nothing to do with AR.
For NAR, you can always use --prefix-mode=1 for simplicity.
