### ISSUE TITLE
why need text-prompts in inference?

### ISSUE THREAD

**Issue by yiwei0730** [lifeiteng/vall-e#146]
If we need to infer a TTS audio in this system, then we maybe just need the audio-prompts and the text which we want to synthesis?
why the text-prompts is needed in inference parser.

**Comment by chenjiasheng** [comment]
because during training we didn't provide the text to the prompt; even more, we didn't distinguish between prompt and target during training.
so, we have to provide as much text prompt as the audio prompt.

**Comment by yiwei0730** [comment]
I find the answer，maybe is the correct。
VALL-E have two result
1. just use the target text and prompt audio
2. use the target text and prompt audio+text ，this called vall-e-continue in the thesis
