### ISSUE TITLE
What are the sponsorship packages?

### ISSUE THREAD

**Issue by ArEnSc** [lifeiteng/vall-e#154]
@lifeiteng Unfortunately when I asked my last question you closed the issues on natural speech 2. but I noticed you have sponsorship I was wondering what the packages were since the alipay link and the other link are not functioning thanks!
We might be able to sponsor you to do this work. If you can setup a patreon that would be cool

**Comment by lifeiteng** [comment]
@ArEnSc my email `lifeiteng0422@163.com`
