### ISSUE TITLE
infer时出现KeyError: 'tʃ' 

### ISSUE THREAD

**Issue by jin1258804025** [lifeiteng/vall-e#166]
python3 bin/infer.py --text-extractor pypinyin_initials_finals --output-dir infer/demos --checkpoint=${exp_dir}/best-valid-loss.pt --text-prompts "甚至出现交易几乎停滞的情况" --audio-prompts ./prompts/ch_24k.wav --text "XXX"

**Comment by jin1258804025** [comment]
命令行添加  --text-extractor pypinyin_initials_finals   英文默认是:espeak

**Comment by nangying1112** [comment]
> 命令行添加 --text-extractor pypinyin_initials_finals 英文默认是:espeak



> python3 bin/infer.py --text-extractor pypinyin_initials_finals --output-dir infer/demos --checkpoint=${exp_dir}/best-valid-loss.pt --text-prompts "甚至出现交易几乎停滞的情况" --audio-prompts ./prompts/ch_24k.wav --text "XXX"

I met the same problem. Could you please share your solution?  Thanks a lot!

**Comment by nangying1112** [comment]
> --text-extractor pypinyin_initials_finals

Got it! Thanks for sharing!
