### ISSUE TITLE
"Segmentation fault" during data preprocessing

### ISSUE THREAD

**Issue by KunZhou9646** [lifeiteng/vall-e#169]
Thanks a lot for your implementation!

During the data pre-processing, I encountered "segmentation fault" issues and still now, don't have a clear idea how to solve it. Could you give me some hints how to solve this issue?
![Screenshot 2023-10-16 at 12 01 49 PM](https://github.com/lifeiteng/vall-e/assets/59918673/b1c741ba-df43-421a-bafc-81ef5f61e6bd)

**Comment by lifeiteng** [comment]
Try the two ways:

1. put blow code into `tokenizer.py` to get error trace
```
import faulthandler
faulthandler.enable()
```
2. try to use CPU when run `tokenizer.py` to get more detail error info

If you find the error, make a pull request to fix it.

**Comment by KunZhou9646** [comment]
It is an incompatible error that indicates espeak was not installed properly. Solved by installing espeak-ng from the source.

**Comment by Dinxin** [comment]
@KunZhou9646 I ran into the same problem. I also installed espeak-ng from the source. But the problem cannot be solved. 
So, how to install espeak-ng from the source properly?

**Comment by KunZhou9646** [comment]
> @KunZhou9646 I ran into the same problem. I also installed espeak-ng from the source. But the problem cannot be solved. So, how to install espeak-ng from the source properly?

Can you check if you config espeak-ng properly?

**Comment by KunZhou9646** [comment]
@Dinxin Can you check if you config espeak-ng properly?
