### ISSUE TITLE
Please change it.

### ISSUE THREAD

**Issue by Arfonium** [lifeiteng/vall-e#171]
You should change SingleCutSampler to SimpleCutSampler in main/valle/data/datamodule.py.
SingleCutSampler is not function of lhotse

**Comment by wrb0312** [comment]
This could be resolved by downgrading lhotse. 
You might want to try running `pip install lhotse==1.16`. 
This should allow you to use the `SingleCutSampler`.

**Comment by lifeiteng** [comment]
@Arfonium DONE https://github.com/lifeiteng/vall-e/pull/173
