### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument weight in method wrapper___slow_conv2d_forward)

### ISSUE THREAD

**Issue by Carebear80** [lifeiteng/vall-e#23]
I get this error after trying:

python3 bin/infer.py \
    --decoder-dim 128 --nhead 4 --num-decoder-layers 4 --model-name valle \
    --text-prompts "Go to her." \
    --audio-prompts ./prompts/61_70970_000007_000001.wav \
    --text "To get up and running quickly just follow the steps below." \
    --output-dir infer/demo_valle_PostNorm_epoch10 \
    --checkpoint exp/valle_nano_v41_PostNorm/epoch-10.pt

I tried poking around infer.py and found:
    

    device = torch.device("cpu")
    
    if torch.cuda.is_available():
        device = torch.device("cuda", 0)
    
    model = get_model(args)
    if args.checkpoint.is_file():
        checkpoint = torch.load(args.checkpoint, map_location=device)
        missing_keys, unexpected_keys = model.load_state_dict(checkpoint["model"], strict=True)
        assert not missing_keys
        # from icefall.checkpoint import save_checkpoint
        # save_checkpoint(f"{args.checkpoint}", model=model)

    model.to(device)
    model.eval()

but I don't see anything wrong with this...

**Comment by sajattack** [comment]
I have a hacky patch for this 
[gpu.patch.txt](https://github.com/lifeiteng/vall-e/files/10727773/gpu.patch.txt)

**Comment by lifeiteng** [comment]
Fixed in https://github.com/lifeiteng/vall-e/pull/24/files

**Comment by Carebear80** [comment]
Ok cool this helps a lot thank you:

        # synthesis
        encoded_frames = model.inference(
            text_tokens, text_tokens_lens, audio_prompts
            text_tokens.to(device),
            text_tokens_lens.to(device),
            audio_prompts.to(device))
