### ISSUE TITLE
what's  the difference with VALL-E and VALL-F?

### ISSUE THREAD

**Issue by yiwei0730** [lifeiteng/vall-e#3]
In your readme, I saw the difference with the seq-to-seq module, what's the effect of this model structure between this two model.

**Comment by lifeiteng** [comment]
VALL-F: Seq2seq TTS (use standard TransformerDecoder)
VALL-E: same as the paper (Modified TransformerDecoder - exclude cross attention, can be implemented by TransformerEncoder)

**Comment by yiwei0730** [comment]
Yes, I think the more parameters not the best choice of the TTS system, we need to find the most fitted system to use!
Maybe it present there are more parameters can be decline.
