### ISSUE TITLE
Training Status

### ISSUE THREAD

**Issue by lifeiteng** [lifeiteng/vall-e#37]
The training is still not converging, I have add some Metrics to minor training https://github.com/lifeiteng/vall-e/pull/31.

This is a freshly built code repository, it may take a little while to get it working.

I will try to solve the problem of convergence on the weekend.

**Comment by lifeiteng** [comment]
in progress, I think `TheTop10Accuracy` should >= 40%
<img width="1757" alt="截屏2023-02-22 20 22 57" src="https://user-images.githubusercontent.com/3107839/220909217-3ab6d55f-d123-4150-8076-ccfa12c65432.png">

**Comment by fullstack-dev0727** [comment]
Hi, @lifeiteng 
I have just trained with following options: 
./run.sh --stage 4 --stop-stage 4 --num-decoder-layers 6 --max-duration 24 --use-fp16 true
Finally I could get epoch-20.pt(3.2GB)

But I have got mismatched audio file that is completely different from text.
python3 bin/infer.py --decoder-dim 1024 --nhead 16 --num-decoder-layers 6 --model-name valle --text-prompts "Go to her." --audio-prompts ./prompts/61_70970_000007_000001.wav --text "To get up and running quickly just follow the steps below." --output-dir infer/demos  --checkpoint exp/valle/epoch-20.pt

Please let me know about the reason.
Thanks very much.
Petar

**Comment by sususpe** [comment]
I also have the same question.  In addition to, I infer many times,  the length of  sentence and audio  is not different, like this,
python bin/infer.py --decoder-dim 128 --nhead 4 --num-decoder-layers 4 --model-name valle --text-prompts "Go to her." --audio-prompts ./prompts/61_70970_000007_000001.wav --text "To get up and running quickly just follow the steps below." --output-dir infer/demos-nano-all --checkpoint exp/valle-nano-all/epoch-15.pt
![image](https://user-images.githubusercontent.com/100407692/221093175-425a8db2-751f-4356-b812-a9b2f74994a0.png)

![image](https://user-images.githubusercontent.com/100407692/221093145-13e25e43-ea1a-4f59-a44b-540d9c172cfd.png)

![image](https://user-images.githubusercontent.com/100407692/221093107-34b9b1d6-e5e0-48e3-9676-081b1b4fba22.png)

**Comment by lifeiteng** [comment]
Fix Top10Accuracy metric  https://github.com/lifeiteng/vall-e/pull/41/commits/eaf88856d1f76c3a87524d601462e8b121a6b0ce

<img width="1764" alt="截屏2023-02-26 17 58 29" src="https://user-images.githubusercontent.com/3107839/221404114-042c3941-2790-48b6-aa2c-1f5900bfc5dd.png">

**Comment by fullstack-dev0727** [comment]
Hi, @lifeiteng 
I have got the issues on training.
./run.sh --stage 4 --stop-stage 4 --num-decoder-layers 6 --max-duration 24 --use-fp16 true

2023-02-27 15:20:52,183 INFO [trainer.py:986] Maximum memory allocated so far is 8112MB
2023-02-27 15:21:05,760 WARNING [trainer.py:656] Grad scale is small: 2.524354896707238e-29
Traceback (most recent call last):
  File "bin/trainer.py", line 1009, in <module>
    main()
  File "bin/trainer.py", line 1002, in main
    run(rank=0, world_size=1, args=args)
  File "bin/trainer.py", line 898, in run
    train_one_epoch(
  File "bin/trainer.py", line 658, in train_one_epoch
    raise RuntimeError(
RuntimeError: grad_scale is too small, exiting: 2.524354896707238e-29

Would you like to check and let me know about the solutions?
Looking forward to hearing from you.
Thanks a lot.
Petar

**Comment by lifeiteng** [comment]
> Hi, @lifeiteng I have got the issues on training. ./run.sh --stage 4 --stop-stage 4 --num-decoder-layers 6 --max-duration 24 --use-fp16 true
> 
> 2023-02-27 15:20:52,183 INFO [trainer.py:986] Maximum memory allocated so far is 8112MB 2023-02-27 15:21:05,760 WARNING [trainer.py:656] Grad scale is small: 2.524354896707238e-29 Traceback (most recent call last): File "bin/trainer.py", line 1009, in main() File "bin/trainer.py", line 1002, in main run(rank=0, world_size=1, args=args) File "bin/trainer.py", line 898, in run train_one_epoch( File "bin/trainer.py", line 658, in train_one_epoch raise RuntimeError( RuntimeError: grad_scale is too small, exiting: 2.524354896707238e-29
> 
> Would you like to check and let me know about the solutions? Looking forward to hearing from you. Thanks a lot. Petar

I updated optim https://github.com/lifeiteng/vall-e/commit/d2740d5748ab31ff0ff5e787a7fe2068585c0e5d

**Comment by fullstack-dev0727** [comment]
Hi, @lifeiteng 
Sorry but I have got the same issue. If use-fp16 == false, it works.

2023-02-27 16:46:34,223 WARNING [trainer.py:656] Grad scale is small: 1.9073486328125e-06
Traceback (most recent call last):
  File "bin/trainer.py", line 1009, in <module>
    main()
  File "bin/trainer.py", line 1002, in main
    run(rank=0, world_size=1, args=args)
  File "bin/trainer.py", line 898, in run
    train_one_epoch(
  File "bin/trainer.py", line 658, in train_one_epoch
    raise RuntimeError(
RuntimeError: grad_scale is too small, exiting: 1.9073486328125e-06

Please check and let me know the solutions.
Thanks

**Comment by fullstack-dev0727** [comment]
Hi, @lifeiteng 
I have added the detailed log.

2023-02-27 16:45:51,210 INFO [trainer.py:666] Epoch 1, batch 4000, train_loss[loss=127, ArTop10Accuracy=0.1077, NarTop10Accuracy=0.005003, over 1202.00 frames. ], tot_loss[loss=90.02, ArTop10Accuracy=0.1558, NarTop10Accuracy=0.009205, over 282881.71 frames. ], batch size: 2, lr: 4.94e-04, grad_scale: 2.0
2023-02-27 16:46:05,036 INFO [trainer.py:666] Epoch 1, batch 4100, train_loss[loss=121.3, ArTop10Accuracy=0.07989, NarTop10Accuracy=0.008289, over 1697.00 frames. ], tot_loss[loss=89.04, ArTop10Accuracy=0.1553, NarTop10Accuracy=0.009654, over 284003.42 frames. ], batch size: 2, lr: 4.88e-04, grad_scale: 1.0
2023-02-27 16:46:20,665 WARNING [trainer.py:656] Grad scale is small: 0.0009765625
2023-02-27 16:46:20,665 INFO [trainer.py:666] Epoch 1, batch 4200, train_loss[loss=23.21, ArTop10Accuracy=0.1494, NarTop10Accuracy=0.006195, over 1641.00 frames. ], tot_loss[loss=nan, ArTop10Accuracy=0.1567, NarTop10Accuracy=0.009837, over 286413.20 frames. ], batch size: 7, lr: 4.82e-04, grad_scale: 0.001953125
2023-02-27 16:46:34,223 WARNING [trainer.py:656] Grad scale is small: 1.9073486328125e-06
Traceback (most recent call last):
  File "bin/trainer.py", line 1009, in <module>
    main()
  File "bin/trainer.py", line 1002, in main
    run(rank=0, world_size=1, args=args)
  File "bin/trainer.py", line 898, in run
    train_one_epoch(
  File "bin/trainer.py", line 658, in train_one_epoch
    raise RuntimeError(
RuntimeError: grad_scale is too small, exiting: 1.9073486328125e-06

Looking forward to hearing from you.
Thanks

**Comment by fullstack-dev0727** [comment]
Hi, @lifeiteng 
Thanks for your work.
I have trained with new run.sh but I have got memory overflow issue.
arguments: --max-duration 24 --num-decoder-layers 6  --use-fp16 false
GPU: Tesla V100 16GB
Would you like to check and let me know about the solutions?
Thanks very much.
Petar

**Comment by sususpe** [comment]
me too. arguments:
 sh run.sh --stage 4 --stop-stage 4 --num-decoder-layers 12 --max-duration 20 --use-fp16 true

**Comment by lifeiteng** [comment]
@fullstack-dev0727  @sususpe  take a look at https://github.com/lifeiteng/vall-e/pull/42

set `--filter-max-duration 12.0` will remove long audio (about 10%)

**Comment by fullstack-dev0727** [comment]
Hi, @lifeiteng 
I have set "--filter-max-duration 12" but memory is increased constantly.
Finally training is failed with memory overflow issue.
Can you help me find the solutions?
Looking forward to hearing from you.
Best Regards!
Petar

**Comment by lifeiteng** [comment]
> Hi, @lifeiteng I have set "--filter-max-duration 12" but memory is increased constantly. Finally training is failed with memory overflow issue. Can you help me find the solutions? Looking forward to hearing from you. Best Regards! Petar

Thank you for reporting this, I have fixed it in https://github.com/lifeiteng/vall-e/pull/42/commits/7725efbec96cbcb31232737f8521d43e78cdc289.

Please feedback me about the FIX.

**Comment by WhiteFu** [comment]
I'm glad to hear of your new improvement! Thanks for your sharing. Are there any good results by improved AR Top10 accuracy? @lifeiteng

**Comment by sususpe** [comment]
Hi, @lifeiteng
I train the model using commit 7725efbec96cbcb31232737f8521d43e78cdc289,and
sh run.sh --stage 4 --stop-stage 4 --num-decoder-layers 12 --max-duration 16  --use-fp16 true &
Finally training is failed with memory overflow issue again.
<img width="1171" alt="image" src="https://user-images.githubusercontent.com/100407692/222624877-961516f5-f6f1-4f88-b428-564a840b2700.png">

Best Regards!
sususpe

**Comment by lifeiteng** [comment]
> Hi, @lifeiteng I train the model using commit [7725efb](https://github.com/lifeiteng/vall-e/commit/7725efbec96cbcb31232737f8521d43e78cdc289),and sh run.sh --stage 4 --stop-stage 4 --num-decoder-layers 12 --max-duration 16 --use-fp16 true & Finally training is failed with memory overflow issue again. <img alt="image" width="1171" src="https://user-images.githubusercontent.com/100407692/222624877-961516f5-f6f1-4f88-b428-564a840b2700.png">
> 
> Best Regards! sususpe

How many steps have been trained?

I think you can run `--max-duration 32 --filter-max-duration 18` with 32G memory.

**Comment by fullstack-dev0727** [comment]
Hi, @lifeiteng 
I trained the model using "bash run.sh --stage 4 --stop-stage 4 --num-decoder-layers 6 --max-duration 24 --filter-max-duration 12 --use-fp16 false" and could get epoch-10.pt file.

When running following command with model, I could not get clean audio.
python3 bin/infer.py --decoder-dim 1024 --nhead 16 --num-decoder-layers 6 --model-name valle --text-prompts "Go to her." --audio-prompts ./prompts/61_70970_000007_000001.wav --text "To get up and running quickly just follow the steps below." --output-dir infer/demos  --checkpoint exp/valle/epoch-10.pt

https://drive.google.com/file/d/1eiuNI6yPBsbIpR20c1CUE6oFBLqVc0Kp/view?usp=sharing

Would you like to check and let me know how to improve?
Thanks for your effort!
Looking forward to hearing from you.
Best Regards!
Petar

**Comment by WhiteFu** [comment]
@fullstack-dev0727 the prompt  text is "To get up and running quickly just follow the steps below." ? I think your result is a little noisy, but the voice can hear the meaning of the text. Maybe let him keep training for a while, and look forward to your new results

**Comment by lifeiteng** [comment]
Fix nan issue in training https://github.com/lifeiteng/vall-e/commit/79200b2a2cea53cd8f853b8bbaceb9963bb786bb

**Comment by lifeiteng** [comment]
After eight hours of training, the model can synthesize natural speech!  https://github.com/lifeiteng/vall-e/issues/53

**Comment by lifeiteng** [comment]
demo and training scripts
https://github.com/lifeiteng/vall-e/tree/main/egs/libritts#demo
