### ISSUE TITLE
times cost and device cost

### ISSUE THREAD

**Issue by yiwei0730** [lifeiteng/vall-e#4]
I want to ask about the data, the time cost and the device cost. 
how many hours Librispeech data did you use? 
How many time cost if your model 100x smaller than the thesis config?
When you train on Librispeech data, Can i know the device cost with memory and batchsize and so on.

**Comment by lifeiteng** [comment]
The nano config can fit on GPU 12 G!
The paper config may need model parallel on multi-gpu(larger gpu).

**Comment by yiwei0730** [comment]
Thanks for your reply 
Can i know what batchsize you used and  how many time cost when you stop the train，how many epochs you run?

**Comment by lifeiteng** [comment]
https://github.com/lifeiteng/vall-e/issues/29
FYI
