### ISSUE TITLE
Very large CUDA memory consumption in rank:0

### ISSUE THREAD

**Issue by XuanGhahahaha** [lifeiteng/vall-e#40]
Hi, great works! Thanks for your sharing!

I have managed to run your preprocessing code. And I have successfully run the training code in a single card. 

But when I run  training in multi 3090 cards. I found the CUDA memory consumption in rank:0 is very large when executing train_one_epoch and after minutes it failed with OOM. Then I found even when the training exited. There are still some processes running in rank:0.

Could you give me some advice solving this problem? Thank you!
![image](https://user-images.githubusercontent.com/73573508/221201565-0a935181-40ef-4739-b165-ad055520a1fb.png)

**Comment by lifeiteng** [comment]
@XuanGhahahaha  Fix this in https://github.com/lifeiteng/vall-e/commit/cfd909c0a67382d9a6702bf2a740e96139bd55cb

**Comment by XuanGhahahaha** [comment]
Great! It works! Thank you for your help.
