### ISSUE TITLE
Problems in tokenizing LibriTTS

### ISSUE THREAD

**Issue by jry-king** [lifeiteng/vall-e#5]
Thanks for your reproduction of the VALL-E paper! When I tried to prepare LibriTTS data with prepare.sh I encountered this problem:
![image](https://user-images.githubusercontent.com/26543484/217235993-e1d0b57c-67a4-4d51-930b-30a0adcf6604.png)
I'm only using 4 tar files (train-clean-100, train-clean-360, test-clean and dev-clean) out of 7 in LibriTTS. Could you give me some suggestions about what's going on? Thanks!

**Comment by lifeiteng** [comment]
datasets fix https://github.com/lifeiteng/vall-e/commit/a23f7c9b3b20a49eb9f14f73766f632491a236a8

**Comment by jry-king** [comment]
Looks like the command is fixed but the "words count mismatch" warning still exists. I only found that it might be caused by some inconsistency between text files and phonemes. Will it actually influence the result?

**Comment by lifeiteng** [comment]
I haven't figured out these warnings yet, I checked the results and there is nothing wrong.

**Comment by mingqilearning** [comment]
@jry-king  Hi, i meet the same warning info, i assume the reason is espeak tokenizer frequently take many words into one phone, e.g. ' of the' to 'ʌvðə'. 
Do you have some solution to fix it, or we can igonre the warning to train the model correctly? Thanks!

**Comment by lifeiteng** [comment]
> @jry-king Hi, i meet the same warning info, i assume the reason is espeak tokenizer frequently take many words into one phone, e.g. ' of the' to 'ʌvðə'. Do you have some solution to fix it, or we can igonre the warning to train the model correctly? Thanks!

can you provide more cases?

we need dig into https://github.com/bootphon/phonemizer.

**Comment by mingqilearning** [comment]
> > @jry-king Hi, i meet the same warning info, i assume the reason is espeak tokenizer frequently take many words into one phone, e.g. ' of the' to 'ʌvðə'. Do you have some solution to fix it, or we can igonre the warning to train the model correctly? Thanks!
> 
it's hard to count them all. i can give you some cases.
"on the floor" to "ɔnðə floːɹ"
"had been" to "hɐdbɪn"
"of a" to "əvə"
"would have" to "wʊdhɐv"
"there is" to "ðɛɹɪz"

**Comment by lifeiteng** [comment]
@jry-king  @mingqilearning  Thank you for report these issues. It would be great if you guys could fix these issues.

Training looks good now https://github.com/lifeiteng/vall-e/issues/37

**Comment by mingqilearning** [comment]
> @jry-king @mingqilearning Thank you for report these issues. It would be great if you guys could fix these issues.
> 
> Training looks good now #37
i tried to fix it, but failed. training good means the warning doesn't influent the training and inference? 
it's great if you share the phomezier and espeak-ng version.

**Comment by lifeiteng** [comment]
https://github.com/espeak-ng/espeak-ng/issues/1703
