### ISSUE TITLE
Support for VALL-E X

### ISSUE THREAD

**Issue by 152334H** [lifeiteng/vall-e#52]
https://vallex-demo.github.io/

Title

**Comment by takan1** [comment]
@lifeiteng Thanks for the great work! Any plan to implement vallex?

**Comment by lifeiteng** [comment]
hands on it now.

**Comment by Li-JEN** [comment]
Hi, @lifeiteng I have tried the vall-ex based on your code. But the modification only on adding the language ID and using the [BigCiDian](https://github.com/speechio/BigCiDian) mentioned in paper as phoneme input.

I utilized LibriTTS and AISHELL3 as data, and below is the preliminary result.
Chinese speaker Audio prompt: [link](https://drive.google.com/file/d/19kSJ8revuqwCG0rFPnalNFVxSLwaascM/view?usp=share_link)

Text: 托管费在基金管理费之外征收
Synthesized Audio: [link](https://drive.google.com/file/d/19kSJ8revuqwCG0rFPnalNFVxSLwaascM/view?usp=share_link)
Text: This I read with great attention while they sat silent.
Synthesized Audio: [link](https://drive.google.com/file/d/1_01IW0Ka6K29JJKyh5MZyFz7DyuFQuL3/view?usp=share_link)

I am not sure if I do it correctly, Maybe I can discuss it with you?
This is my email: [mail](mailto:ss95471998@gmail.com)

**Comment by misakaikato** [comment]
> hi, the link to the first audio you synthesized using the prompt seems to be wrong, and now it's still that prompt.

朋友，中文合成的第一条链接好像是错误的，打开还是那个prompt的文件。😂

**Comment by thomasbohm** [comment]
@lifeiteng Hey thanks for the efforts! Any update on **VALL-E X**?

**Comment by skysbird** [comment]
> Hi, @lifeiteng I have tried the vall-ex based on your code. But the modification only on adding the language ID and using the [BigCiDian](https://github.com/speechio/BigCiDian) mentioned in paper as phoneme input.
> 
> I utilized LibriTTS and AISHELL3 as data, and below is the preliminary result. Chinese speaker Audio prompt: [link](https://drive.google.com/file/d/19kSJ8revuqwCG0rFPnalNFVxSLwaascM/view?usp=share_link)
> 
> Text: 托管费在基金管理费之外征收 Synthesized Audio: [link](https://drive.google.com/file/d/1r1NQQonKw11ACflDtvZPQoBxAGjMms-_/view?usp=share_link) Text: This I read with great attention while they sat silent. Synthesized Audio: [link](https://drive.google.com/file/d/1_01IW0Ka6K29JJKyh5MZyFz7DyuFQuL3/view?usp=share_link)
> 
> I am not sure if I do it correctly, Maybe I can discuss it with you? This is my email: [mail](mailto:rokfarmerslowly2@gmail.com)

same to me, my solution is same as you. it seems works

**Comment by RahulBhalley** [comment]
> > Hi, @lifeiteng I have tried the vall-ex based on your code. But the modification only on adding the language ID and using the [BigCiDian](https://github.com/speechio/BigCiDian) mentioned in paper as phoneme input.
> > I utilized LibriTTS and AISHELL3 as data, and below is the preliminary result. Chinese speaker Audio prompt: [link](https://drive.google.com/file/d/19kSJ8revuqwCG0rFPnalNFVxSLwaascM/view?usp=share_link)
> > Text: 托管费在基金管理费之外征收 Synthesized Audio: [link](https://drive.google.com/file/d/1r1NQQonKw11ACflDtvZPQoBxAGjMms-_/view?usp=share_link) Text: This I read with great attention while they sat silent. Synthesized Audio: [link](https://drive.google.com/file/d/1_01IW0Ka6K29JJKyh5MZyFz7DyuFQuL3/view?usp=share_link)
> > I am not sure if I do it correctly, Maybe I can discuss it with you? This is my email: [mail](mailto:rokfarmerslowly2@gmail.com)
> 
> same to me, my solution is same as you. it seems works

अपने VALLE-X को कैसे इंप्लीमेंट किया?

**Comment by skysbird** [comment]
> 

maybe you can refer to my e-x branch forked from here

**Comment by RahulBhalley** [comment]
आपके रेपॉजिटरी में VALLE-X से संबंधित कोई कोड अपडेट दिखाई नहीं दे रहा है।
@skysbird

**Comment by Li-JEN** [comment]
> > 
> 
> maybe you can refer to my e-x branch forked from here

@skysbird How do you handle the part of Language ID? I saw your code, but it seems like you follow the architecture of origin Vall-E?

**Comment by skysbird** [comment]
> > > 
> > 
> > maybe you can refer to my e-x branch forked from here
> 
> @skysbird How do you handle the part of Language ID? I saw your code, but it seems like you follow the architecture of origin Vall-E?

I have embedded language id

**Comment by RahulBhalley** [comment]
> > > maybe you can refer to my e-x branch forked from here
> > 
> > 
> > @skysbird How do you handle the part of Language ID? I saw your code, but it seems like you follow the architecture of origin Vall-E?
> 
> I have embedded language id

Can you please drop a link to that code statement?

**Comment by treya-lin** [comment]
So is there any update on implementing VALL-E X?
