### ISSUE TITLE
any windows install document

### ISSUE THREAD

**Issue by witchfindertr** [lifeiteng/vall-e#57]
anyone have how to install on windows

**Comment by JacksonMeade** [comment]
I know this is an imperfect answer but...
What I did was download Ubuntu 20 LTS from the Microsoft Store with [WSL2](https://learn.microsoft.com/en-us/windows/wsl/install) and followed the instructions from there.

The only major hiccup is you'll need to make sure you install cuDNN and CUDA drivers on Ubuntu/WSL.

To do that, follow the instructions [here](https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html#installlinux-deb).

Getting drivers/downloads from these places:

- [Game Ready Driver Download](https://www.nvidia.com/download/index.aspx)
- [cuDNN download](https://developer.nvidia.com/rdp/cudnn-download)

**Comment by cwjacklin** [comment]
i ran on Win11 without WSL

1) espeak-ng not found:   set PHONEMIZER_ESPEAK_LIBRARY,  PHONEMIZER_ESPEAK_PATH  https://github.com/bootphon/phonemizer/issues/44  
2) need 11.6 cudatoolkit:  no cuda found error: copy MSVS build extensions from cuda to MSVS buildtools folder https://github.com/NVlabs/tiny-cuda-nn/issues/164 
3) k2 use win install wheels https://k2-fsa.org/nightly/index.html 
4) POSIX error from pathlib
pathlib.PosixPath = pathlib.WindowsPath

**Comment by makingmusic** [comment]
i have been able to install vall-e and related dependencies it on windows, but could not run the steps as mentioned in the egs/librtts/prepare.sh (which is originally built for bash). Is there an alternate ?
