### ISSUE TITLE
excuse me, how much times  on the preprocess the audio dataset?

### ISSUE THREAD

**Issue by friendmine** [lifeiteng/vall-e#75]
excuse me, how much times  on the preprocess the audio dataset?
I want to use the whisper to get the script,
but it maybe take about 1 minute to extract 10minutes audio.
maybe will take about several hours for the dataset LibriTTS

**Comment by lifeiteng** [comment]
@friendmine It's more faster now https://github.com/lifeiteng/vall-e/pull/88
