### ISSUE TITLE
A solution to the bug of AR and NAR training separately on DDP

### ISSUE THREAD

**Issue by guokr233** [lifeiteng/vall-e#76]
modify train.py
<img width="965" alt="image" src="https://user-images.githubusercontent.com/43952592/229496551-ae5fae62-57e2-44e0-9467-7a2996a4efb2.png">
to

```
    if params.train_stage:
        if world_size > 1:
            stage_named_parameters = model.module.stage_named_parameters(params.train_stage)
            model_parameters = model.module.stage_parameters(params.train_stage)
        else:
            stage_named_parameters = model.stage_named_parameters(params.train_stage)
            model_parameters = model.stage_parameters(params.train_stage)
    else:
        model_parameters = model.parameters()


    if params.optimizer_name == "ScaledAdam":
        parameters_names = []
        if params.train_stage:  # != 0
            parameters_names.append(
                [
                    name_param_pair[0]
                    for name_param_pair in stage_named_parameters
                ]
            )

**Comment by lifeiteng** [comment]
@guokr233  can you provide the error message? I did't have two GPUs.

**Comment by guokr233** [comment]
> @guokr233 can you provide the error message? I did't have two GPUs.

in train.py, line 891
> model_parameters = model.stage_parameters(params.train_stage)
model object have no attribute stage_parameters

because it's a DDP object, so I use the 'model.module'

**Comment by lifeiteng** [comment]
solved in https://github.com/lifeiteng/vall-e/pull/59/commits/7d6b721d5c63c9bd025f33b2b2873d2d4515a99a
