### ISSUE TITLE
Got silence audio after inference

### ISSUE THREAD

**Issue by jry-king** [lifeiteng/vall-e#8]
I followed the steps in installation section in README and trained a valle model with this config
`python3 bin/trainer.py \
    --decoder-dim 128 --nhead 4 --num-decoder-layers 4 \
    --max-duration 40 --model-name valle \
    --exp-dir exp/valle_nano_full
`
Then I tried to synthesize audio with the inference code given but got an audio file with nothing in it. The command line looks like this
![image](https://user-images.githubusercontent.com/26543484/217497354-1ffb06c2-49c6-443d-8fb1-85aed341cbad.png)
What could I do to solve this problem? Thanks!

**Comment by lifeiteng** [comment]
nano config is too small, so the AR-Decoder may not work well.
re-run to get new(diverse) result.
