### ISSUE TITLE
Prompt concatenation 

### ISSUE THREAD

**Issue by terboo54** [lifeiteng/vall-e#80]
I'm just wondering what are you doing during training and inference, 

during the training you are using the the same audio (including the text of that audio) as the text and the prompt right? 

I mean 
let's assume you have the below data

```
Audio A | speaker x | chunk1 | some text here 1 |
Audio A | speaker x | chunk2 | some text here 2 |
Audio A | speaker x | chunk3 | some text here 3|
Audio B | speaker x | chunk1 | some text here 4|
Audio B | speaker x | chunk2 | some text here 5|
```

during training you are passing the below (for one example of the batch)

the input text
```
some text here 3 some text here 2 
```
the input speech
```
chunk3 + gap + chunk2
```
and you only mask the acoustic content of chunk2 to be predicted, while chunk3 is the acoustic input prompt and the concatenation of both text 3 and text 2 is the input prompt

is that what are you doing or I'm wrong?

**Comment by terboo54** [comment]
@lifeiteng I would appreciate your input

**Comment by lifeiteng** [comment]
`(text3 + text2 + chunk3 + chunk2, Mask)` is treated as the inputs of DecoderOnly Transformer

In AR Decoder: I use causal mask(e.g. autoregressive), The audo tokens 1, ..., t, ... T -> DuringTraining 1:t can be treated as "prompt", **Inference is same as Training**.

In NAR Decoder: we should prepare prompt chunk in --prefix-mode 1 2 4, we sum all code matrix like the paper.

**The principle of making an algorithm model is that training and inference should be as consistent as possible.** 
My implementation follows this principle.
