### ISSUE TITLE
File needed for inference

### ISSUE THREAD

**Issue by nivibilla** [lifeiteng/vall-e#91]
I'm trying to do inference using the checkpoint from #58 . But I need the file unique_text_tokens.k2symbols.

Is there any way to create it again?

@dohe0342
Tagging for reference

**Comment by cwjacklin** [comment]
correct me if i'm wrong.   it's in egs\libritts\data\tokenized

**Comment by nivibilla** [comment]
Yes you are absolutely correct. I am stupid. Thanks!

**Comment by catalwaysright** [comment]
Did you run the infer.py successfully? I got missing keys and unexpected keys error.

**Comment by nivibilla** [comment]
I got cuda out of memory unfortunately. I'm trying to adapt the model to use BitsandBytes.

**Comment by temporaryharry** [comment]
Can someone please send me the  unique_text_tokens.k2symbols as you need to train the thing and is not in the github repo. Please send it to grandmaskisses342@gmail.com or send the drive link please and thanks

**Comment by chenjiasheng** [comment]
@temporaryharry please check git history, as I remebered, that file used to be in git repo.
